### ISSUE TITLE
Feature request: Slight tweak to workflow needed.

### ISSUE THREAD

**Issue by carlca** [766b/vscode-go-outliner#9]
This is already a very useful extension. I especially like the way that if you right-click on the outline, it allows you to navigate with the keyboard before pressing enter to return focus to the editor panel. One tweak which would allow total keyboard use would be a shortcut key combination to shift focus to the outline panel in the first place.

**Comment by 766b** [comment]
It's already possible to do so, if you search your keybindings for `workbench.view.extension.go-outliner` and assign a shortcut for it, then once pressed it will jump back to an extension. If you already had it opened before, then it will jump to previously selected item, otherwise it will just open the tab. Unfortunately if you use explorer extension, then it will not jump to it, and instead open the main extension tab.

Is this what you wanted?
